### ISSUE TITLE
config_mysql.php

### ISSUE THREAD

**Issue by an9n6m97s** [eodclan/xucp#1]
Hello, i created a database and i connect him, but i have this issue.

 **Warning: mysqli_connect() expects parameter 5 to be int, string given in /home/r102465redl/ucp.redlife.ro/include/config/config_mysql.php on line 56
Database connection could not be queried!**

**Comment by eodclan** [comment]
Check your MySQL Database Server Port.

**Comment by an9n6m97s** [comment]
I checked and continue i have this error.

**Warning: mysqli_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/r102465redl/ucp.redlife.ro/include/config/config_mysql.php on line 56

Warning: mysqli_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/r102465redl/ucp.redlife.ro/include/config/config_mysql.php on line 56
Database connection could not be queried!**

**Comment by eodclan** [comment]
check my faqs from my website https://derstr1k3r.de/pages/faqs/
